### ISSUE TITLE
Unable to run due to ModuleNotFoundError: No module named' importlib. metadata '

### ISSUE THREAD

**Issue by Rhein-momo** [HCGB-IGTP/BacterialTyper#26]
Traceback (most recent call last):
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/bin/BacterialTyper", line 12, in <module>
    import BacterialTyper.modules
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/__init__.py", line 22, in <module>
    from BacterialTyper import *
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/modules/__init__.py", line 25, in <module>
    from BacterialTyper.modules import *
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/modules/annot.py", line 20, in <module>
    from BacterialTyper.config import set_config
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/config/__init__.py", line 7, in <module>
    from BacterialTyper.config import *
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/config/extern_progs.py", line 29, in <module>
    from BacterialTyper.scripts import functions
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/scripts/__init__.py", line 27, in <module>
    from BacterialTyper.scripts import *
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/scripts/database_generator.py", line 33, in <module>
    from BacterialTyper.scripts import min_hash_caller
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/BacterialTyper/scripts/min_hash_caller.py", line 33, in <module>
    import sourmash
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/sourmash/__init__.py", line 113, in <module>
    from . import lca
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/sourmash/lca/__init__.py", line 8, in <module>
    from .command_index import index
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/sourmash/lca/command_index.py", line 9, in <module>
    from sourmash import sourmash_args
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/sourmash/sourmash_args.py", line 46, in <module>
    import screed
  File "/home/momo/mambaforge/envs/BacterialTyper_mamba/lib/python3.7/site-packages/screed/__init__.py", line 39, in <module>
    from importlib.metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib.metadata'

**Comment by Rhein-momo** [comment]
I reinstalled importlib-metadata=4.5.0, but the issue hasn't been resolved
